import Link from "next/link";
import { site } from "@/content/site";
import { projects } from "@/content/projects";
import { about, experience } from "@/content/experience";
import { ProjectCard } from "@/components/ProjectCard";

const section = "mx-auto max-w-[1200px] px-5 sm:px-8";
const personJsonLd = { "@context": "https://schema.org", "@type": "Person", name: site.name, jobTitle: site.role, email: `mailto:${site.email}`, url: site.url || undefined, sameAs: [site.github, site.linkedin], alumniOf: { "@type": "CollegeOrUniversity", name: "University of Washington" }, worksFor: experience.filter((r) => r.end === null).map((r) => ({ "@type": "Organization", name: r.org })) };

export default function Home() {
  const [ring, gnome, ...supporting] = projects;
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }} />
    <section className={`${section} relative overflow-hidden py-16 sm:py-24 lg:py-28`}>
      <div className="topo-motif pointer-events-none absolute -right-32 -top-20 h-[480px] w-[620px] opacity-60" aria-hidden="true" />
      <div className="relative grid gap-12 lg:grid-cols-[1fr_0.8fr] lg:items-center lg:gap-20">
        <div><p className="field-note text-accent-secondary">Nikhil George · Seattle, WA</p><h1 className="mt-5 max-w-[760px] text-[46px] sm:text-[64px] lg:text-[78px]">I turn noisy signals into systems people can trust.</h1><p className="measure mt-6 text-[18px] text-text-muted sm:text-[20px]">I’m a UW computer science student and software engineer working across embedded devices, cloud infrastructure, and human-centered products.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#work" className="inline-flex min-h-11 items-center rounded-sm bg-accent px-5 text-[15px] font-medium text-background hover:opacity-85">Explore selected systems</Link><Link href="/resume" className="inline-flex min-h-11 items-center rounded-sm border border-border px-5 text-[15px] hover:border-accent">Résumé</Link><a href={site.github} className="inline-flex min-h-11 items-center rounded-sm border border-border px-5 text-[15px] hover:border-accent">GitHub</a></div></div>
        <SignalVisual />
      </div>
    </section>

    <section id="work" className={`${section} scroll-mt-20 py-16 sm:py-20`}><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="field-note text-accent-secondary">Selected systems</p><h2 className="mt-2 text-[36px] sm:text-[44px]">Signal → System → Decision</h2></div><p className="max-w-sm text-[15px] text-text-muted">Projects shaped by the physical world, careful measurement, and the people who use the result.</p></div><div className="mt-10 space-y-6"><ProjectCard project={ring} /><ProjectCard project={gnome} reverse /><div className="grid gap-6 md:grid-cols-2">{supporting.map((p) => <ProjectCard key={p.slug} project={p} compact />)}</div></div></section>

    <section className="border-y border-border bg-surface/60"><div className={`${section} py-14 sm:py-16`}><div className="flex flex-wrap items-baseline justify-between gap-4"><h2 className="text-[32px] sm:text-[38px]">How I work</h2><p className="field-note text-text-muted">Observe → Decode → Build → Validate</p></div><ol className="mt-9 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{[["01", "Observe", "Start with the environment, the constraint, and the person affected."], ["02", "Decode", "Make the signal legible, whether it arrives as bytes, readings, or behavior."], ["03", "Build", "Carry the constraint through firmware, infrastructure, and interface."], ["04", "Validate", "Cross-check the output and keep the unknowns visible."]].map(([n, title, body]) => <li key={title} className="border-l-2 border-accent pl-4"><span className="field-note text-text-muted">{n}</span><h3 className="mt-2 text-[20px]">{title}</h3><p className="mt-1 text-[14px] text-text-muted">{body}</p></li>)}</ol></div></section>

    <section id="experience" className={`${section} scroll-mt-20 py-16 sm:py-20`}><p className="field-note text-accent-secondary">Context</p><h2 className="mt-2 text-[36px] sm:text-[44px]">Experience</h2><ol className="mt-9 divide-y divide-border border-y border-border">{experience.map((r) => <li key={`${r.org}-${r.title}`} className="grid gap-4 py-7 md:grid-cols-[0.7fr_1.3fr] md:gap-12"><div><h3 className="text-[21px]">{r.org}</h3><p className="text-[15px] text-text-muted">{r.title}</p><p className="mt-1 font-mono text-[11px] text-text-muted">{r.start} — {r.end ?? "Present"}</p></div><div><p className="measure text-[16px]">{r.summary}</p>{r.points.length > 0 && <ul className="mt-3 space-y-2 text-[14px] text-text-muted">{r.points.slice(0, 2).map((p) => <li key={p} className="flex gap-2"><span className="mt-3 size-1.5 shrink-0 rounded-full bg-accent" />{p}</li>)}</ul>}</div></li>)}</ol></section>

    <section id="about" className="scroll-mt-20 border-t border-border bg-accent-soft/35"><div className={`${section} grid gap-8 py-16 sm:py-20 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20`}><div><p className="field-note text-accent-secondary">The human side</p><h2 className="mt-2 text-[36px] sm:text-[44px]">About</h2></div><div className="measure space-y-5 text-[18px]">{about.map((p) => <p key={p}>{p}</p>)}</div></div></section>

    <section id="contact" className={`${section} scroll-mt-20 py-16 sm:py-20`}><p className="field-note text-accent-secondary">Open channel</p><h2 className="mt-2 max-w-2xl text-[38px] sm:text-[50px]">Interested in systems that connect hardware, software, and people? Let’s talk.</h2><p className="mt-5 text-[16px] text-text-muted">{site.availability}</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-[16px]"><a className="link-underline text-accent" href={`mailto:${site.email}`}>Email</a><a className="link-underline text-accent" href={site.linkedin}>LinkedIn</a><a className="link-underline text-accent" href={site.github}>GitHub</a><Link className="link-underline text-accent" href="/resume">Résumé</Link></div></section>
  </>;
}

function SignalVisual() {
  return <div className="relative min-h-[330px] overflow-hidden rounded-card border border-border bg-surface p-5 sm:min-h-[390px] sm:p-8"><p className="field-note text-text-muted">A working thesis</p><svg viewBox="0 0 520 300" className="mt-5 w-full" role="img" aria-labelledby="signal-title signal-desc"><title id="signal-title">Signal to system to decision</title><desc id="signal-desc">A measured signal becomes a structured system and a human decision.</desc><path d="M10 110 C50 40 70 190 112 105 S165 55 202 144 S258 190 292 110" fill="none" stroke="var(--rain)" strokeWidth="2" className="signal-trace"/><path d="M292 110 C330 110 330 70 365 70 L450 70" fill="none" stroke="var(--accent)" strokeWidth="2"/><path d="M292 110 C330 110 330 150 365 150 L450 150" fill="none" stroke="var(--accent-secondary)" strokeWidth="2"/><circle cx="292" cy="110" r="7" fill="var(--blossom)"/><circle cx="450" cy="70" r="6" fill="var(--accent)"/><circle cx="450" cy="150" r="6" fill="var(--accent-secondary)"/></svg><div className="absolute bottom-6 left-5 right-5 grid grid-cols-3 gap-2 sm:left-8 sm:right-8"><div><p className="field-note text-text-muted">01</p><p className="mt-1 text-[15px]">Signal</p></div><div><p className="field-note text-text-muted">02</p><p className="mt-1 text-[15px]">System</p></div><div><p className="field-note text-text-muted">03</p><p className="mt-1 text-[15px]">Decision</p></div></div></div>;
}
